sample:
  vocab_dim: 32

resume_train:
  resume_train: False
  ckpt_name: ./
  checkpoint_path: ./
  start_epoch: 0

dataset:
  name: CrossDock
  data_base: /home/haotian/Molecule_Generation/Res2Mol/data/crossdocked_pocket10
  split: /home/haotian/Molecule_Generation/Res2Mol/data/split_by_name.pt
  use_cache: True